export const Mods = {
  'Customizable Slimes': [
    'AdvancedConfig',
    'AdditionalConfig',
    'BehavioursConfig',
    'CustomSlime',
    'CustomMesh',
    'CustomPlort',
    'EatMapConfig',
    'LargoProperties',
    'SpawnZoneConfig',
    'StructureConfig',
    'StyleAppearance',
    'StyleCosmetic',
  ],
  'Customizable Slimes 2': [
    'AdvancedConfig',
    'AdditionalConfig',
    'BehavioursConfig',
    'CustomSlime',
    'CustomMesh',
    'CustomPlort',
    'EatMapConfig',
    'LargoProperties',
    'SpawnZoneConfig',
    'StructureConfig',
    'StyleAppearance',
    'StyleCosmetic',
  ],
};
